[theme]
base = "light"
primaryColor = "#074A7A"
backgroundColor = "#F7F4EE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2D2926"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[ui]
hideTopBar = false
